// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {time} from '../models';

export function AddIncome(arg1:number):Promise<string>;

export function AddInvestments(arg1:string,arg2:number,arg3:number):Promise<string>;

export function AddMoneySpent(arg1:number,arg2:string):Promise<string>;

export function AddReoccuringCost(arg1:number,arg2:string,arg3:number,arg4:string):Promise<string>;

export function AddReoccuringIncome(arg1:number):Promise<string>;

export function DomReady(arg1:context.Context):Promise<void>;

export function GetAllIncome():Promise<string>;

export function GetAllInvestments():Promise<string>;

export function GetAllSpentMoney():Promise<string>;

export function GetCurrMonthIncome(arg1:string):Promise<string>;

export function GetMonthMoneySpent(arg1:string):Promise<string>;

export function GetRangeDataIncome(arg1:time.Time,arg2:time.Time):Promise<void>;

export function GetRangeDataSpent(arg1:time.Time,arg2:time.Time):Promise<void>;

export function ImportInvestments():Promise<string>;

export function ImportTransactions():Promise<string>;

export function RemoveMoneySpent(arg1:number):Promise<string>;
