// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIncome(arg1) {
  return window['go']['app']['App']['AddIncome'](arg1);
}

export function AddInvestments(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddInvestments'](arg1, arg2, arg3);
}

export function AddMoneySpent(arg1, arg2) {
  return window['go']['app']['App']['AddMoneySpent'](arg1, arg2);
}

export function AddReoccuringCost(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddReoccuringCost'](arg1, arg2, arg3, arg4);
}

export function AddReoccuringIncome(arg1) {
  return window['go']['app']['App']['AddReoccuringIncome'](arg1);
}

export function DomReady(arg1) {
  return window['go']['app']['App']['DomReady'](arg1);
}

export function GetAllIncome() {
  return window['go']['app']['App']['GetAllIncome']();
}

export function GetAllInvestments() {
  return window['go']['app']['App']['GetAllInvestments']();
}

export function GetAllSpentMoney() {
  return window['go']['app']['App']['GetAllSpentMoney']();
}

export function GetCurrMonthIncome(arg1) {
  return window['go']['app']['App']['GetCurrMonthIncome'](arg1);
}

export function GetMonthMoneySpent(arg1) {
  return window['go']['app']['App']['GetMonthMoneySpent'](arg1);
}

export function GetRangeDataIncome(arg1, arg2) {
  return window['go']['app']['App']['GetRangeDataIncome'](arg1, arg2);
}

export function GetRangeDataSpent(arg1, arg2) {
  return window['go']['app']['App']['GetRangeDataSpent'](arg1, arg2);
}

export function ImportInvestments() {
  return window['go']['app']['App']['ImportInvestments']();
}

export function ImportTransactions() {
  return window['go']['app']['App']['ImportTransactions']();
}

export function RemoveMoneySpent(arg1) {
  return window['go']['app']['App']['RemoveMoneySpent'](arg1);
}
